/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.109
 * Generated at: 2025-12-15 07:06:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import in.co.rays.proj4.util.DataUtility;
import in.co.rays.proj4.util.ServletUtility;
import in.co.rays.proj4.controller.LoginCtl;
import in.co.rays.proj4.controller.UserRegistrationCtl;
import in.co.rays.proj4.util.HTMLUtility;
import java.util.HashMap;
import java.util.Map;
import in.co.rays.proj4.controller.ORSView;
import in.co.rays.proj4.controller.ORSView;
import in.co.rays.proj4.controller.LoginCtl;
import in.co.rays.proj4.bean.UserBean;
import in.co.rays.proj4.bean.RoleBean;

public final class LoginView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/jsp/Header.jsp", Long.valueOf(1765782354538L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(14);
    _jspx_imports_classes.add("in.co.rays.proj4.controller.UserRegistrationCtl");
    _jspx_imports_classes.add("in.co.rays.proj4.controller.ORSView");
    _jspx_imports_classes.add("in.co.rays.proj4.controller.LoginCtl");
    _jspx_imports_classes.add("in.co.rays.proj4.bean.UserBean");
    _jspx_imports_classes.add("in.co.rays.proj4.util.DataUtility");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("in.co.rays.proj4.util.HTMLUtility");
    _jspx_imports_classes.add("in.co.rays.proj4.util.ServletUtility");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("in.co.rays.proj4.bean.RoleBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Header</title>\r\n");
      out.write("\r\n");
      out.write("<!-- JQuery -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.4.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.13.2/jquery-ui.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"/ORSProject-04/js/checkbox.js\"></script>\r\n");
      out.write("<script src=\"/ORSProject-04/js/datepicker.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Logo -->\r\n");
      out.write("<img src=\"");
      out.print(request.getContextPath());
      out.write("/img/customLogo.jpg\" align=\"right\"\r\n");
      out.write("     width=\"100\" height=\"40\" border=\"0\">\r\n");
      out.write("\r\n");

    UserBean user = (UserBean) session.getAttribute("user");
    boolean loggedIn = user != null;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Logged In View -->\r\n");
 if (loggedIn) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <h3>Hi, ");
      out.print(user.getFirstName());
      out.write(' ');
      out.write('(');
      out.print(session.getAttribute("role"));
      out.write(")</h3>\r\n");
      out.write("\r\n");
      out.write("    <!-- Common menus -->\r\n");
      out.write("    <a href=\"");
      out.print(ORSView.MY_PROFILE_CTL);
      out.write("\"><b>My Profile</b></a> |\r\n");
      out.write("    <a href=\"");
      out.print(ORSView.CHANGE_PASSWORD_CTL);
      out.write("\"><b>Change Password</b></a> |\r\n");
      out.write("    <a href=\"");
      out.print(ORSView.GET_MARKSHEET_CTL);
      out.write("\"><b>Get Marksheet</b></a> |\r\n");
      out.write("    <a href=\"");
      out.print(ORSView.MARKSHEET_MERIT_LIST_CTL);
      out.write("\"><b>Merit List</b></a> |\r\n");
      out.write("\r\n");
      out.write("    <!-- Admin Only -->\r\n");
      out.write("    ");
 if (user.getRoleId() == RoleBean.ADMIN) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.USER_CTL);
      out.write("\"><b>Add User</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.USER_LIST_CTL);
      out.write("\"><b>User List</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.ROLE_CTL);
      out.write("\"><b>Add Role</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.ROLE_LIST_CTL);
      out.write("\"><b>Role List</b></a> |\r\n");
      out.write("\r\n");
      out.write("        <!-- College menus (Admin only since College role removed) -->\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.COLLEGE_CTL);
      out.write("\"><b>Add College</b></a> |\r\n");
      out.write("         <a href=\"");
      out.print(ORSView.COLLEGE_LIST_CTL);
      out.write("\"><b>College List</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.PATIENT_CTL);
      out.write("\"><b>Add Patient</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.PATIENT_LIST_CTL);
      out.write("\"><b>Patient List</b></a> |\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Faculty + Admin Menus (College role replaced with Faculty) -->\r\n");
      out.write("    ");
 if (user.getRoleId() == RoleBean.FACULTY || user.getRoleId() == RoleBean.ADMIN) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.STUDENT_CTL);
      out.write("\"><b>Add Student</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.STUDENT_LIST_CTL);
      out.write("\"><b>Student List</b></a> |\r\n");
      out.write("\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.MARKSHEET_CTL);
      out.write("\"><b>Add Marksheet</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.MARKSHEET_LIST_CTL);
      out.write("\"><b>Marksheet List</b></a> |\r\n");
      out.write("\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.COURSE_CTL);
      out.write("\"><b>Add Course</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.COURSE_LIST_CTL);
      out.write("\"><b>Course List</b></a> |\r\n");
      out.write("\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.SUBJECT_CTL);
      out.write("\"><b>Add Subject</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.SUBJECT_LIST_CTL);
      out.write("\"><b>Subject List</b></a> |\r\n");
      out.write("\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.FACULTY_CTL);
      out.write("\"><b>Add Faculty</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.FACULTY_LIST_CTL);
      out.write("\"><b>Faculty List</b></a> |\r\n");
      out.write("\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.TIMETABLE_CTL);
      out.write("\"><b>Add Timetable</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.TIMETABLE_LIST_CTL);
      out.write("\"><b>Timetable List</b></a> |\r\n");
      out.write("\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Admin Only -->\r\n");
      out.write("    <a href=\"");
      out.print(ORSView.JAVA_DOC);
      out.write("\" target=\"blank\"><b>Java Doc</b></a> |\r\n");
      out.write("\r\n");
      out.write("    <!-- Logout -->\r\n");
      out.write("    <a href=\"");
      out.print(ORSView.LOGIN_CTL);
      out.write("?operation=");
      out.print(LoginCtl.OP_LOG_OUT);
      out.write("\"><b>Logout</b></a>\r\n");
      out.write("\r\n");
 } else { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Guest View -->\r\n");
      out.write("    <h3>Hi, Guest</h3>\r\n");
      out.write("    <a href=\"WelcomeCtl\"><b>Welcome</b></a> |\r\n");
      out.write("    <a href=\"LoginCtl\"><b>Login</b></a>\r\n");
      out.write("\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("	<form action=\"");
      out.print(ORSView.LOGIN_CTL);
      out.write("\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("		");
      in.co.rays.proj4.bean.UserBean bean = null;
      bean = (in.co.rays.proj4.bean.UserBean) _jspx_page_context.getAttribute("bean", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (bean == null){
        bean = new in.co.rays.proj4.bean.UserBean();
        _jspx_page_context.setAttribute("bean", bean, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div align=\"center\">\r\n");
      out.write("			<h1>Login</h1>\r\n");
      out.write("			\r\n");
      out.write("			<div style=\"height: 15px; margin-bottom: 12px\">\r\n");
      out.write("				<H3 align=\"center\">\r\n");
      out.write("					<font color=\"green\"> ");
      out.print(ServletUtility.getSuccessMessage(request));
      out.write("\r\n");
      out.write("					</font>\r\n");
      out.write("				</H3>\r\n");
      out.write("				<H3 align=\"center\">\r\n");
      out.write("					<font color=\"red\"> ");
      out.print(ServletUtility.getErrorMessage(request));
      out.write("\r\n");
      out.write("					</font>\r\n");
      out.write("				</H3>\r\n");
      out.write("			</div>\r\n");
      out.write("			");

				String uri = (String) request.getAttribute("uri");
			
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			<table>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>Login ID:</th>\r\n");
      out.write("					<td><input type=\"text\" name=\"login\" placeholder=\"Enter Your E-mail\"\r\n");
      out.write("						value=\"");
      out.print(DataUtility.getStringData(bean.getLogin()));
      out.write("\"></td>\r\n");
      out.write("					<td style=\"position: fixed;\"><font color=\"red\"> ");
      out.print(ServletUtility.getErrorMessage("login", request));
      out.write("</font></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>Password:</th>\r\n");
      out.write("					<td><input type=\"text\" name=\"password\" placeholder=\"Enter Your Password\"\r\n");
      out.write("						value=\"");
      out.print(DataUtility.getStringData(bean.getPassword()));
      out.write("\"></td>\r\n");
      out.write("					<td style=\"position: fixed;\"><font color=\"red\"> ");
      out.print(ServletUtility.getErrorMessage("password", request));
      out.write("</font></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td></td>\r\n");
      out.write("					<td><input type=\"submit\" name=\"operation\"\r\n");
      out.write("						value=\"");
      out.print(LoginCtl.OP_SIGN_IN);
      out.write("\"> <input type=\"submit\"\r\n");
      out.write("						name=\"operation\" value=\"");
      out.print(LoginCtl.OP_SIGN_UP);
      out.write("\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th></th>\r\n");
      out.write("					<td></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th></th>\r\n");
      out.write("					<td><a href=\"");
      out.print(ORSView.FORGET_PASSWORD_CTL);
      out.write("\"><b>Forget my password?</b></a>&nbsp;</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("			<input type=\"hidden\" name=\"uri\" value=\"");
      out.print(uri);
      out.write("\">\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
